---
deployment:
  tasks:
    - export DEPLOYPATH=/home/jhfxa9ujppkg/public_html/
    - /bin/cp -R bin $DEPLOYPATH
    - /bin/cp -R node_modules $DEPLOYPATH
    - /bin/cp -R public $DEPLOYPATH
    - /bin/cp -R routes $DEPLOYPATH
    - /bin/cp -R views $DEPLOYPATH
    - /bin/cp app.js $DEPLOYPATH
    - /bin/cp package-lock.json $DEPLOYPATH
    - /bin/cp package.json $DEPLOYPATH
